#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-partitions
Version  : 1.10.9
Release  : 44
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/partitions_1.10-9.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/partitions_1.10-9.tar.gz
Summary  : Additive Partitions of Integers
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-partitions-lib = %{version}-%{release}
Requires: R-Rdpack
Requires: R-gmp
Requires: R-polynom
Requires: R-sets
BuildRequires : R-Rdpack
BuildRequires : R-gmp
BuildRequires : R-polynom
BuildRequires : R-sets
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
partitions, unequal partitions, and restricted partitions of an
  integer; the three corresponding partition functions are also given.
  Set partitions and now compositions and riffle shuffles are
  included.

%package lib
Summary: lib components for the R-partitions package.
Group: Libraries

%description lib
lib components for the R-partitions package.


%prep
%setup -q -n partitions
pushd ..
cp -a partitions buildavx2
popd
pushd ..
cp -a partitions buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746043518

%install
export SOURCE_DATE_EPOCH=1746043518
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/partitions/CITATION
/usr/lib64/R/library/partitions/DESCRIPTION
/usr/lib64/R/library/partitions/INDEX
/usr/lib64/R/library/partitions/Meta/Rd.rds
/usr/lib64/R/library/partitions/Meta/features.rds
/usr/lib64/R/library/partitions/Meta/hsearch.rds
/usr/lib64/R/library/partitions/Meta/links.rds
/usr/lib64/R/library/partitions/Meta/nsInfo.rds
/usr/lib64/R/library/partitions/Meta/package.rds
/usr/lib64/R/library/partitions/Meta/vignette.rds
/usr/lib64/R/library/partitions/NAMESPACE
/usr/lib64/R/library/partitions/R/partitions
/usr/lib64/R/library/partitions/R/partitions.rdb
/usr/lib64/R/library/partitions/R/partitions.rdx
/usr/lib64/R/library/partitions/doc/index.html
/usr/lib64/R/library/partitions/doc/partitions.R
/usr/lib64/R/library/partitions/doc/partitions.Rnw
/usr/lib64/R/library/partitions/doc/partitions.pdf
/usr/lib64/R/library/partitions/doc/scrabble.R
/usr/lib64/R/library/partitions/doc/scrabble.Rnw
/usr/lib64/R/library/partitions/doc/scrabble.pdf
/usr/lib64/R/library/partitions/doc/setpartitions.R
/usr/lib64/R/library/partitions/doc/setpartitions.Rnw
/usr/lib64/R/library/partitions/doc/setpartitions.pdf
/usr/lib64/R/library/partitions/help/AnIndex
/usr/lib64/R/library/partitions/help/aliases.rds
/usr/lib64/R/library/partitions/help/figures/partitions.png
/usr/lib64/R/library/partitions/help/partitions.rdb
/usr/lib64/R/library/partitions/help/partitions.rdx
/usr/lib64/R/library/partitions/help/paths.rds
/usr/lib64/R/library/partitions/html/00Index.html
/usr/lib64/R/library/partitions/html/R.css
/usr/lib64/R/library/partitions/tests/testthat.R
/usr/lib64/R/library/partitions/tests/testthat/test_aaa.R
/usr/lib64/R/library/partitions/tests/testthat/test_aab.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/partitions/libs/partitions.so
/V4/usr/lib64/R/library/partitions/libs/partitions.so
/usr/lib64/R/library/partitions/libs/partitions.so
